packages:
  - 'ui'
  - 'widgets/**'

catalog:
  react: "^18.3.1"
  react-compiler-runtime: "^19.1.0-rc.2"
  react-dom: "^18.3.1"
  zebar: "^3.1.0"
  tailwindcss: "^3.4.15"
  "@types/react": "^18.3.18"
  "@types/react-dom": "^18.3.5"


